/**
 * Definición de los Patrones Funcionales de Gordon
 * MVP: Nutricional-Metabólico, Sueño-Descanso, Tolerancia al Estrés
 */

export interface PatternField {
  id: string;
  label: string;
  type: 'toggle' | 'slider' | 'select' | 'text' | 'number' | 'multiselect' | 'body_map';
  options?: { label: string; value: string }[];
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  isSeedQuestion?: boolean;
  showWhen?: { fieldId: string; value: unknown };
  required?: boolean;
  placeholder?: string;
}

export interface PatternDefinition {
  id: string;
  name: string;
  icon: string;
  color: string;
  description: string;
  fields: PatternField[];
  isMvp: boolean;
}

export const PATTERNS: PatternDefinition[] = [
  {
    id: 'nutritional',
    name: 'Nutricional-Metabólico',
    icon: '🍎',
    color: '#22C55E',
    description: 'Evalúa el estado nutricional, metabólico e integridad de la piel.',
    isMvp: true,
    fields: [
      {
        id: 'weight',
        label: 'Peso (kg)',
        type: 'number',
        min: 20,
        max: 250,
        unit: 'kg',
        required: true,
        placeholder: 'Ej: 72.5',
      },
      {
        id: 'height',
        label: 'Talla (m)',
        type: 'number',
        min: 0.5,
        max: 2.5,
        step: 0.01,
        unit: 'm',
        required: true,
        placeholder: 'Ej: 1.68',
      },
      {
        id: 'appetite',
        label: 'Apetito',
        type: 'select',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Aumentado', value: 'increased' },
          { label: 'Disminuido', value: 'decreased' },
          { label: 'Ausente', value: 'absent' },
        ],
        required: true,
      },
      {
        id: 'swallowing_difficulty',
        label: '¿Dificultad para deglutir?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'swallowing_type',
        label: 'Tipo de disfagia',
        type: 'select',
        options: [
          { label: 'Sólidos', value: 'solids' },
          { label: 'Líquidos', value: 'liquids' },
          { label: 'Ambos', value: 'both' },
        ],
        showWhen: { fieldId: 'swallowing_difficulty', value: true },
      },
      {
        id: 'nausea_vomiting',
        label: '¿Náuseas o vómitos?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'vomiting_frequency',
        label: 'Frecuencia de vómitos (veces/día)',
        type: 'slider',
        min: 1,
        max: 10,
        step: 1,
        showWhen: { fieldId: 'nausea_vomiting', value: true },
      },
      {
        id: 'oral_condition',
        label: 'Estado de mucosa oral',
        type: 'select',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Seca', value: 'dry' },
          { label: 'Con lesiones', value: 'lesions' },
          { label: 'Inflamada', value: 'inflamed' },
        ],
        required: true,
      },
      {
        id: 'skin_turgor',
        label: 'Turgencia de la piel',
        type: 'select',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Disminuida', value: 'decreased' },
          { label: 'Aumentada', value: 'increased' },
        ],
      },
      {
        id: 'edema_present',
        label: '¿Presencia de edema?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'edema_locations',
        label: 'Localización del edema',
        type: 'body_map',
        showWhen: { fieldId: 'edema_present', value: true },
      },
      {
        id: 'skin_lesions',
        label: '¿Lesiones en piel?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'lesion_locations',
        label: 'Localización de lesiones',
        type: 'body_map',
        showWhen: { fieldId: 'skin_lesions', value: true },
      },
      {
        id: 'lesion_type',
        label: 'Tipo de lesión',
        type: 'multiselect',
        options: [
          { label: 'Úlcera por presión', value: 'pressure_ulcer' },
          { label: 'Herida quirúrgica', value: 'surgical_wound' },
          { label: 'Quemadura', value: 'burn' },
          { label: 'Dermatitis', value: 'dermatitis' },
          { label: 'Otra', value: 'other' },
        ],
        showWhen: { fieldId: 'skin_lesions', value: true },
      },
      {
        id: 'glucose',
        label: 'Glucosa (mg/dL)',
        type: 'number',
        min: 30,
        max: 600,
        unit: 'mg/dL',
        placeholder: 'Ej: 110',
      },
      {
        id: 'albumin',
        label: 'Albúmina (g/dL)',
        type: 'number',
        min: 0.5,
        max: 7,
        step: 0.1,
        unit: 'g/dL',
        placeholder: 'Ej: 3.5',
      },
    ],
  },
  {
    id: 'sleep',
    name: 'Sueño-Descanso',
    icon: '🌙',
    color: '#6366F1',
    description: 'Evalúa la calidad y cantidad del sueño y descanso.',
    isMvp: true,
    fields: [
      {
        id: 'sleep_normal',
        label: '¿Patrón de sueño sin alteraciones?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'hours_sleep',
        label: 'Horas de sueño por noche',
        type: 'slider',
        min: 0,
        max: 14,
        step: 0.5,
        unit: 'horas',
        showWhen: { fieldId: 'sleep_normal', value: false },
      },
      {
        id: 'sleep_quality',
        label: 'Calidad del sueño',
        type: 'select',
        options: [
          { label: 'Buena', value: 'good' },
          { label: 'Regular', value: 'fair' },
          { label: 'Mala', value: 'poor' },
        ],
        showWhen: { fieldId: 'sleep_normal', value: false },
      },
      {
        id: 'insomnia',
        label: 'Tipo de insomnio',
        type: 'select',
        options: [
          { label: 'Ninguno', value: 'none' },
          { label: 'De conciliación', value: 'onset' },
          { label: 'De mantenimiento', value: 'maintenance' },
          { label: 'Despertar temprano', value: 'early_waking' },
        ],
        showWhen: { fieldId: 'sleep_normal', value: false },
      },
      {
        id: 'sleep_aids',
        label: '¿Usa medicación para dormir?',
        type: 'toggle',
        showWhen: { fieldId: 'sleep_normal', value: false },
      },
      {
        id: 'sleep_aid_name',
        label: 'Nombre del medicamento',
        type: 'text',
        showWhen: { fieldId: 'sleep_aids', value: true },
        placeholder: 'Ej: Zolpidem 10mg',
      },
      {
        id: 'fatigue_level',
        label: 'Nivel de fatiga diurna',
        type: 'slider',
        min: 0,
        max: 10,
        step: 1,
        showWhen: { fieldId: 'sleep_normal', value: false },
      },
      {
        id: 'sleep_environment',
        label: 'Factores ambientales que afectan el sueño',
        type: 'multiselect',
        options: [
          { label: 'Ruido', value: 'noise' },
          { label: 'Luz', value: 'light' },
          { label: 'Temperatura', value: 'temperature' },
          { label: 'Dolor', value: 'pain' },
          { label: 'Ansiedad', value: 'anxiety' },
        ],
        showWhen: { fieldId: 'sleep_normal', value: false },
      },
    ],
  },
  {
    id: 'stress',
    name: 'Tolerancia al Estrés',
    icon: '🧠',
    color: '#F59E0B',
    description: 'Evalúa los niveles de estrés, afrontamiento y adaptación.',
    isMvp: true,
    fields: [
      {
        id: 'stress_level',
        label: 'Nivel de estrés percibido',
        type: 'select',
        options: [
          { label: 'Bajo', value: 'low' },
          { label: 'Moderado', value: 'moderate' },
          { label: 'Alto', value: 'high' },
          { label: 'Severo', value: 'severe' },
        ],
        required: true,
      },
      {
        id: 'coping_strategy',
        label: 'Estrategia de afrontamiento',
        type: 'select',
        options: [
          { label: 'Adecuada', value: 'adequate' },
          { label: 'Inadecuada', value: 'inadequate' },
          { label: 'Ausente', value: 'absent' },
        ],
        required: true,
      },
      {
        id: 'anxiety_signs',
        label: '¿Manifiesta signos de ansiedad?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'anxiety_symptoms',
        label: 'Síntomas de ansiedad',
        type: 'multiselect',
        options: [
          { label: 'Taquicardia', value: 'tachycardia' },
          { label: 'Diaforesis', value: 'diaphoresis' },
          { label: 'Temblor', value: 'tremor' },
          { label: 'Inquietud', value: 'restlessness' },
          { label: 'Llanto', value: 'crying' },
          { label: 'Nerviosismo', value: 'nervousness' },
        ],
        showWhen: { fieldId: 'anxiety_signs', value: true },
      },
      {
        id: 'support_system',
        label: '¿Cuenta con sistema de apoyo?',
        type: 'toggle',
      },
      {
        id: 'support_type',
        label: 'Tipo de apoyo',
        type: 'multiselect',
        options: [
          { label: 'Familia', value: 'family' },
          { label: 'Amigos', value: 'friends' },
          { label: 'Religión/Espiritualidad', value: 'religion' },
          { label: 'Profesional (Psicólogo)', value: 'professional' },
          { label: 'Grupos de apoyo', value: 'support_groups' },
        ],
        showWhen: { fieldId: 'support_system', value: true },
      },
      {
        id: 'recent_changes',
        label: 'Cambios recientes significativos',
        type: 'multiselect',
        options: [
          { label: 'Pérdida familiar', value: 'family_loss' },
          { label: 'Cambio de empleo', value: 'job_change' },
          { label: 'Diagnóstico nuevo', value: 'new_diagnosis' },
          { label: 'Hospitalización', value: 'hospitalization' },
          { label: 'Cambio de domicilio', value: 'relocation' },
        ],
      },
      {
        id: 'emotional_state',
        label: 'Estado emocional actual',
        type: 'select',
        options: [
          { label: 'Estable / Tranquilo', value: 'stable' },
          { label: 'Irritable', value: 'irritable' },
          { label: 'Triste / Deprimido', value: 'sad' },
          { label: 'Temeroso', value: 'fearful' },
          { label: 'Enojado', value: 'angry' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'perception',
    name: 'Percepción-Manejo de Salud',
    icon: '🏥',
    color: '#3B82F6',
    description: 'Evalúa la percepción del paciente sobre su salud y cómo la maneja.',
    isMvp: true,
    fields: [
      {
        id: 'health_perception',
        label: '¿Cómo percibe su estado de salud actual?',
        type: 'select',
        options: [
          { label: 'Bueno', value: 'good' },
          { label: 'Regular', value: 'fair' },
          { label: 'Malo', value: 'poor' },
        ],
        required: true,
      },
      {
        id: 'knows_diagnosis',
        label: '¿Conoce su diagnóstico?',
        type: 'toggle',
      },
      {
        id: 'follows_treatment',
        label: '¿Sigue indicaciones médicas?',
        type: 'toggle',
      },
      {
        id: 'treatment_adherence',
        label: 'Adherencia al tratamiento',
        type: 'select',
        options: [
          { label: 'Completa', value: 'complete' },
          { label: 'Parcial', value: 'partial' },
          { label: 'Nula', value: 'none' },
        ],
      },
      {
        id: 'substance_use',
        label: 'Consumo de sustancias',
        type: 'multiselect',
        options: [
          { label: 'Ninguna', value: 'none' },
          { label: 'Tabaco', value: 'tobacco' },
          { label: 'Alcohol', value: 'alcohol' },
          { label: 'Drogas', value: 'drugs' },
          { label: 'Automedicación', value: 'self_medication' },
        ],
      },
      {
        id: 'vaccination_status',
        label: 'Esquema de vacunación',
        type: 'select',
        options: [
          { label: 'Completo', value: 'complete' },
          { label: 'Incompleto', value: 'incomplete' },
          { label: 'Desconocido', value: 'unknown' },
        ],
      },
      {
        id: 'hospitalization_history',
        label: '¿Hospitalizaciones previas?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'hospitalization_reason',
        label: 'Motivo de hospitalización previa',
        type: 'text',
        showWhen: { fieldId: 'hospitalization_history', value: true },
        placeholder: 'Ej: Cirugía de apéndice',
      },
      {
        id: 'health_notes',
        label: 'Observaciones adicionales',
        type: 'text',
        placeholder: 'Notas relevantes...',
      },
    ],
  },
  {
    id: 'elimination',
    name: 'Eliminación',
    icon: '💧',
    color: '#06B6D4',
    description: 'Evalúa los patrones de eliminación urinaria, intestinal y cutánea.',
    isMvp: true,
    fields: [
      {
        id: 'urinary_normal',
        label: '¿Eliminación urinaria sin alteraciones?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'urinary_frequency',
        label: 'Frecuencia urinaria (veces/día)',
        type: 'slider',
        min: 0,
        max: 20,
        step: 1,
        showWhen: { fieldId: 'urinary_normal', value: false },
      },
      {
        id: 'urinary_symptoms',
        label: 'Síntomas urinarios',
        type: 'multiselect',
        options: [
          { label: 'Disuria (dolor)', value: 'dysuria' },
          { label: 'Retención urinaria', value: 'retention' },
          { label: 'Incontinencia', value: 'incontinence' },
          { label: 'Urgencia', value: 'urgency' },
          { label: 'Hematuria', value: 'hematuria' },
          { label: 'Nicturia', value: 'nocturia' },
        ],
        showWhen: { fieldId: 'urinary_normal', value: false },
      },
      {
        id: 'urinary_device',
        label: '¿Usa dispositivo urinario?',
        type: 'select',
        options: [
          { label: 'Ninguno', value: 'none' },
          { label: 'Sonda Foley', value: 'foley' },
          { label: 'Sonda intermitente', value: 'intermittent' },
          { label: 'Pañal', value: 'diaper' },
        ],
        showWhen: { fieldId: 'urinary_normal', value: false },
      },
      {
        id: 'bowel_normal',
        label: '¿Eliminación intestinal sin alteraciones?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'bowel_frequency',
        label: 'Frecuencia intestinal',
        type: 'select',
        options: [
          { label: 'Diaria', value: 'daily' },
          { label: 'Cada 2-3 días', value: 'every_2_3' },
          { label: 'Semanal o menos', value: 'weekly' },
          { label: 'Varias al día', value: 'multiple_daily' },
        ],
        showWhen: { fieldId: 'bowel_normal', value: false },
      },
      {
        id: 'stool_consistency',
        label: 'Consistencia de heces',
        type: 'select',
        options: [
          { label: 'Normal / Formada', value: 'normal' },
          { label: 'Dura', value: 'hard' },
          { label: 'Blanda', value: 'soft' },
          { label: 'Líquida (diarrea)', value: 'liquid' },
          { label: 'Con sangre', value: 'bloody' },
        ],
        showWhen: { fieldId: 'bowel_normal', value: false },
      },
      {
        id: 'bowel_symptoms',
        label: 'Síntomas intestinales',
        type: 'multiselect',
        options: [
          { label: 'Estreñimiento', value: 'constipation' },
          { label: 'Diarrea', value: 'diarrhea' },
          { label: 'Flatulencia', value: 'flatulence' },
          { label: 'Distensión abdominal', value: 'distension' },
          { label: 'Dolor abdominal', value: 'abdominal_pain' },
        ],
        showWhen: { fieldId: 'bowel_normal', value: false },
      },
      {
        id: 'diaphoresis',
        label: '¿Diaforesis (sudoración excesiva)?',
        type: 'toggle',
      },
    ],
  },
  {
    id: 'activity',
    name: 'Actividad-Ejercicio',
    icon: '🏃',
    color: '#10B981',
    description: 'Evalúa la capacidad de actividad física, movilidad y autocuidado.',
    isMvp: true,
    fields: [
      {
        id: 'mobility_level',
        label: 'Nivel de movilidad',
        type: 'select',
        options: [
          { label: 'Independiente', value: 'independent' },
          { label: 'Requiere ayuda parcial', value: 'partial_help' },
          { label: 'Requiere ayuda total', value: 'total_help' },
          { label: 'Postrado en cama', value: 'bedridden' },
        ],
        required: true,
      },
      {
        id: 'exercise_frequency',
        label: 'Actividad física habitual',
        type: 'select',
        options: [
          { label: 'Sedentario', value: 'sedentary' },
          { label: '1-2 veces/semana', value: 'low' },
          { label: '3-4 veces/semana', value: 'moderate' },
          { label: 'Diario', value: 'daily' },
        ],
      },
      {
        id: 'dyspnea',
        label: '¿Presenta disnea (falta de aire)?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'dyspnea_type',
        label: 'Tipo de disnea',
        type: 'select',
        options: [
          { label: 'De esfuerzo', value: 'exertional' },
          { label: 'En reposo', value: 'rest' },
          { label: 'Nocturna', value: 'nocturnal' },
          { label: 'Ortopnea', value: 'orthopnea' },
        ],
        showWhen: { fieldId: 'dyspnea', value: true },
      },
      {
        id: 'heart_rate',
        label: 'Frecuencia cardíaca (lpm)',
        type: 'number',
        min: 30,
        max: 220,
        unit: 'lpm',
        placeholder: 'Ej: 72',
      },
      {
        id: 'blood_pressure_sys',
        label: 'Presión arterial sistólica (mmHg)',
        type: 'number',
        min: 60,
        max: 300,
        unit: 'mmHg',
        placeholder: 'Ej: 120',
      },
      {
        id: 'blood_pressure_dia',
        label: 'Presión arterial diastólica (mmHg)',
        type: 'number',
        min: 30,
        max: 200,
        unit: 'mmHg',
        placeholder: 'Ej: 80',
      },
      {
        id: 'oxygen_saturation',
        label: 'Saturación de oxígeno (%)',
        type: 'number',
        min: 50,
        max: 100,
        unit: '%',
        placeholder: 'Ej: 97',
      },
      {
        id: 'assistive_devices',
        label: 'Dispositivos de asistencia',
        type: 'multiselect',
        options: [
          { label: 'Ninguno', value: 'none' },
          { label: 'Bastón', value: 'cane' },
          { label: 'Andador', value: 'walker' },
          { label: 'Silla de ruedas', value: 'wheelchair' },
          { label: 'Oxígeno suplementario', value: 'oxygen' },
        ],
      },
      {
        id: 'self_care_deficit',
        label: '¿Déficit de autocuidado?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'self_care_areas',
        label: 'Áreas de déficit',
        type: 'multiselect',
        options: [
          { label: 'Alimentación', value: 'feeding' },
          { label: 'Baño / Higiene', value: 'bathing' },
          { label: 'Vestido', value: 'dressing' },
          { label: 'Uso del baño', value: 'toileting' },
        ],
        showWhen: { fieldId: 'self_care_deficit', value: true },
      },
    ],
  },
  {
    id: 'cognitive',
    name: 'Cognitivo-Perceptual',
    icon: '👁️',
    color: '#8B5CF6',
    description: 'Evalúa funciones cognitivas, sensoriales y percepción del dolor.',
    isMvp: true,
    fields: [
      {
        id: 'consciousness_level',
        label: 'Nivel de conciencia',
        type: 'select',
        options: [
          { label: 'Alerta', value: 'alert' },
          { label: 'Somnoliento', value: 'drowsy' },
          { label: 'Confuso', value: 'confused' },
          { label: 'Estuporoso', value: 'stuporous' },
          { label: 'Inconsciente', value: 'unconscious' },
        ],
        required: true,
      },
      {
        id: 'orientation',
        label: 'Orientación',
        type: 'multiselect',
        options: [
          { label: 'Tiempo', value: 'time' },
          { label: 'Espacio', value: 'space' },
          { label: 'Persona', value: 'person' },
        ],
      },
      {
        id: 'pain_present',
        label: '¿Presenta dolor?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'pain_level',
        label: 'Nivel de dolor (EVA)',
        type: 'slider',
        min: 0,
        max: 10,
        step: 1,
        showWhen: { fieldId: 'pain_present', value: true },
      },
      {
        id: 'pain_location',
        label: 'Localización del dolor',
        type: 'text',
        showWhen: { fieldId: 'pain_present', value: true },
        placeholder: 'Ej: Abdomen superior',
      },
      {
        id: 'pain_type',
        label: 'Tipo de dolor',
        type: 'select',
        options: [
          { label: 'Agudo', value: 'acute' },
          { label: 'Crónico', value: 'chronic' },
          { label: 'Neuropático', value: 'neuropathic' },
          { label: 'Visceral', value: 'visceral' },
        ],
        showWhen: { fieldId: 'pain_present', value: true },
      },
      {
        id: 'sensory_deficits',
        label: 'Déficits sensoriales',
        type: 'multiselect',
        options: [
          { label: 'Ninguno', value: 'none' },
          { label: 'Visual', value: 'visual' },
          { label: 'Auditivo', value: 'auditory' },
          { label: 'Táctil', value: 'tactile' },
          { label: 'Olfativo', value: 'olfactory' },
          { label: 'Gustativo', value: 'gustatory' },
        ],
      },
      {
        id: 'communication_ability',
        label: 'Capacidad de comunicación',
        type: 'select',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Alterada (disartria)', value: 'dysarthria' },
          { label: 'Afasia', value: 'aphasia' },
          { label: 'Intubado / No verbal', value: 'non_verbal' },
        ],
      },
      {
        id: 'memory_issues',
        label: '¿Alteraciones de memoria?',
        type: 'toggle',
      },
    ],
  },
  {
    id: 'self_perception',
    name: 'Autopercepción-Autoconcepto',
    icon: '🪞',
    color: '#EC4899',
    description: 'Evalúa la imagen corporal, autoestima e identidad personal.',
    isMvp: true,
    fields: [
      {
        id: 'self_esteem',
        label: 'Nivel de autoestima',
        type: 'select',
        options: [
          { label: 'Alta / Positiva', value: 'high' },
          { label: 'Normal', value: 'normal' },
          { label: 'Baja', value: 'low' },
          { label: 'Muy baja', value: 'very_low' },
        ],
        required: true,
      },
      {
        id: 'body_image_disturbance',
        label: '¿Alteración de la imagen corporal?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'body_image_cause',
        label: 'Causa de alteración',
        type: 'multiselect',
        options: [
          { label: 'Cirugía reciente', value: 'surgery' },
          { label: 'Amputación', value: 'amputation' },
          { label: 'Cambio de peso', value: 'weight_change' },
          { label: 'Cicatrices', value: 'scars' },
          { label: 'Enfermedad crónica', value: 'chronic_illness' },
        ],
        showWhen: { fieldId: 'body_image_disturbance', value: true },
      },
      {
        id: 'expresses_hopelessness',
        label: '¿Expresa sentimientos de desesperanza?',
        type: 'toggle',
      },
      {
        id: 'expresses_worthlessness',
        label: '¿Se siente inútil o sin valor?',
        type: 'toggle',
      },
      {
        id: 'self_perception_notes',
        label: 'Observaciones sobre autopercepción',
        type: 'text',
        placeholder: 'Notas adicionales...',
      },
    ],
  },
  {
    id: 'role',
    name: 'Rol-Relaciones',
    icon: '👥',
    color: '#F97316',
    description: 'Evalúa los roles familiares, laborales y las relaciones interpersonales.',
    isMvp: true,
    fields: [
      {
        id: 'family_structure',
        label: 'Estructura familiar',
        type: 'select',
        options: [
          { label: 'Nuclear (pareja e hijos)', value: 'nuclear' },
          { label: 'Extendida', value: 'extended' },
          { label: 'Monoparental', value: 'single_parent' },
          { label: 'Vive solo/a', value: 'alone' },
          { label: 'Institucionalizado', value: 'institutionalized' },
        ],
        required: true,
      },
      {
        id: 'primary_caregiver',
        label: '¿Tiene cuidador principal?',
        type: 'toggle',
      },
      {
        id: 'role_changes',
        label: '¿Cambios en roles recientes?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'role_change_type',
        label: 'Tipo de cambio de rol',
        type: 'multiselect',
        options: [
          { label: 'Laboral', value: 'work' },
          { label: 'Familiar', value: 'family' },
          { label: 'Social', value: 'social' },
          { label: 'Pérdida de independencia', value: 'independence_loss' },
        ],
        showWhen: { fieldId: 'role_changes', value: true },
      },
      {
        id: 'interpersonal_conflicts',
        label: '¿Conflictos interpersonales?',
        type: 'toggle',
      },
      {
        id: 'social_isolation',
        label: '¿Se siente aislado socialmente?',
        type: 'toggle',
      },
      {
        id: 'domestic_violence',
        label: '¿Indicios de violencia doméstica?',
        type: 'toggle',
      },
      {
        id: 'role_notes',
        label: 'Observaciones sobre roles',
        type: 'text',
        placeholder: 'Notas adicionales...',
      },
    ],
  },
  {
    id: 'sexuality',
    name: 'Sexualidad-Reproducción',
    icon: '♀️',
    color: '#E11D48',
    description: 'Evalúa el patrón reproductivo y las preocupaciones sexuales.',
    isMvp: true,
    fields: [
      {
        id: 'sexual_concerns',
        label: '¿Presenta preocupaciones sobre su sexualidad?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'sexual_concern_type',
        label: 'Tipo de preocupación',
        type: 'multiselect',
        options: [
          { label: 'Disfunción sexual', value: 'dysfunction' },
          { label: 'Cambios por enfermedad', value: 'illness_changes' },
          { label: 'Efectos de medicamentos', value: 'medication_effects' },
          { label: 'Imagen corporal', value: 'body_image' },
        ],
        showWhen: { fieldId: 'sexual_concerns', value: true },
      },
      {
        id: 'menstrual_status',
        label: 'Estado menstrual (si aplica)',
        type: 'select',
        options: [
          { label: 'No aplica', value: 'na' },
          { label: 'Regular', value: 'regular' },
          { label: 'Irregular', value: 'irregular' },
          { label: 'Amenorrea', value: 'amenorrhea' },
          { label: 'Menopausia', value: 'menopause' },
          { label: 'Embarazo', value: 'pregnancy' },
        ],
      },
      {
        id: 'contraception',
        label: 'Método anticonceptivo (si aplica)',
        type: 'select',
        options: [
          { label: 'No aplica', value: 'na' },
          { label: 'Ninguno', value: 'none' },
          { label: 'Hormonal', value: 'hormonal' },
          { label: 'Barrera', value: 'barrier' },
          { label: 'DIU', value: 'iud' },
          { label: 'Quirúrgico', value: 'surgical' },
        ],
      },
      {
        id: 'sexuality_notes',
        label: 'Observaciones',
        type: 'text',
        placeholder: 'Notas adicionales...',
      },
    ],
  },
  {
    id: 'values',
    name: 'Valores-Creencias',
    icon: '🙏',
    color: '#A855F7',
    description: 'Evalúa el sistema de valores, creencias y prácticas espirituales.',
    isMvp: true,
    fields: [
      {
        id: 'religion',
        label: 'Religión o creencia espiritual',
        type: 'select',
        options: [
          { label: 'Ninguna', value: 'none' },
          { label: 'Católica', value: 'catholic' },
          { label: 'Cristiana / Evangélica', value: 'christian' },
          { label: 'Otra', value: 'other' },
        ],
      },
      {
        id: 'spiritual_support',
        label: '¿Desea apoyo espiritual?',
        type: 'toggle',
      },
      {
        id: 'spiritual_distress',
        label: '¿Expresa sufrimiento espiritual?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'spiritual_distress_type',
        label: 'Manifestaciones de sufrimiento espiritual',
        type: 'multiselect',
        options: [
          { label: 'Cuestiona el sentido de la vida', value: 'meaning' },
          { label: 'Cuestiona su fe', value: 'faith' },
          { label: 'Culpa', value: 'guilt' },
          { label: 'Miedo a la muerte', value: 'death_fear' },
          { label: 'Desesperanza espiritual', value: 'hopelessness' },
        ],
        showWhen: { fieldId: 'spiritual_distress', value: true },
      },
      {
        id: 'treatment_beliefs',
        label: '¿Sus creencias afectan el tratamiento?',
        type: 'toggle',
        isSeedQuestion: true,
      },
      {
        id: 'treatment_beliefs_detail',
        label: '¿De qué manera?',
        type: 'text',
        showWhen: { fieldId: 'treatment_beliefs', value: true },
        placeholder: 'Ej: Rechaza transfusiones por creencia religiosa',
      },
      {
        id: 'values_notes',
        label: 'Observaciones sobre valores y creencias',
        type: 'text',
        placeholder: 'Notas adicionales...',
      },
    ],
  },
];
